### ISSUE TITLE
Proto files with names containing - are not translated to _

### ISSUE THREAD

**Issue by Amoratinos** [crflynn/protobuf-init#6]
I've been using this plugin to generate __init__ files but I've found that if a proto file contains a `-` when the init file is built that character is not replaced by `_` as grpc_tools does. 

e.g:
`catalog-metadata.proto` is added like `from .catalog-metadata_pb2 import.....` when it should be `from .catalog_metadata_pb2 import ...`

**Comment by crflynn** [comment]
Should be fixed in 0.1.2
